name: omniscan-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - httpx
  - pip
  - flake8
  - pytest
  - pip:
      - fastapi==0.110.0
      - uvicorn==0.27.1
      - starlette
      - python-multipart  # <--- ADD THIS LINE
